# Python CircleCI 2.0 configuration file:
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

defaults: &defaults
  working_directory: ~/lolstats/server
  docker:
    - image: circleci/python:3.6.1


machine:
  python:
    version: 3.6.1

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout:
          path: ~/lolstats
      - restore_cache:
          key: dependency-cache-{{ checksum "requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install -r requirements.txt
      - save_cache:
          key: dependency-cache-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: build failed notification
          command: |
              . venv/bin/activate
              python3 bot.py """BUILD ${CIRCLE_BUILD_NUM} FAILED :/
              User: ${CIRCLE_USERNAME}
              Branch: ${CIRCLE_BRANCH}
              CI: ${CIRCLE_BUILD_URL}"""
          when: on_fail


    # run tests!
    # this example uses Django's built-in test-runner
    # other common Python testing frameworks include pytest and nose
    # https://pytest.org
    # https://nose.readthedocs.io
  test:
    <<: *defaults
    steps:
      - checkout:
          path: ~/lolstats
      - restore_cache:
          key: dependency-cache-{{ checksum "requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install -r requirements.txt
      - save_cache:
          key: dependency-cache-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: run tests
          command:
            echo "Testing..."
      - run:
          name: tests failed notification
          command: |
              . venv/bin/activate
              python3 bot.py """TESTS FAILED :/
              User: ${CIRCLE_USERNAME}
              Branch: ${CIRCLE_BRANCH}
              CI: ${CIRCLE_BUILD_URL}"""
          when: on_fail
  notifySuccess:
    <<: *defaults
    steps:
      - checkout:
          path: ~/lolstats
      - restore_cache:
          key: dependency-cache-{{ checksum "requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install -r requirements.txt
      - save_cache:
          key: dependency-cache-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: ci success notification
          command: |
              . venv/bin/activate
              python3 bot.py """Master Ci pipeline passed! :D
              CI: ${CIRCLE_BUILD_URL}"""


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - notifySuccess:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
